[env:esp32-s3-devkitm-1]
platform = espressif32
board = esp32-s3-devkitm-1
framework = arduino
monitor_speed = 115200
lib_deps =
    adafruit/DHT sensor library @ ^1.4.6
    adafruit/Adafruit Unified Sensor @ ^1.1.14
    marcoschwartz/LiquidCrystal_I2C @ ^1.1.2
    knolleary/PubSubClient @ ^2.8
    bblanchon/ArduinoJson @ ^7.0.4
    eloquentarduino/EloquentTensorFlow32 @ ^1.0.0
    tanakamasayuki/TensorFlowLite_ESP32 @ ^1.0.0
