[env:uno]
platform = atmelavr
board = uno
framework = arduino

; Serial Monitor Options
monitor_speed = 115200

; Library Dependencies
lib_deps =
    sandeepmistry/LoRa @ ^0.8.0
    marcoschwartz/LiquidCrystal_I2C @ ^1.1.2
    bblanchon/ArduinoJson @ ^7.0.0
    feilipu/FreeRTOS @ ^11.1.0-2 